
### Koefisien Determinasi

Koefisien determinasi, sering disimbolkan sebagai r², adalah suatu ukuran yang memberikan informasi tentang seberapa baik model regresi linear mampu menjelaskan variasi total dari peubah respon. Koefisien determinasi berkisar antara 0 hingga 1.

Secara konsep, r² menjelaskan proporsi dari variasi total dalam peubah respon yang dapat dijelaskan oleh peubah prediktor yang ada dalam model regresi. Nilai yang lebih tinggi menunjukkan bahwa model regresi lebih baik dalam menjelaskan variasi data. Di sisi lain, r² yang rendah mungkin menunjukkan bahwa model tidak secara efektif menjelaskan variasi yang diamati dalam data.

- **r² = 0** : Model regresi tidak menjelaskan variasi apa pun dalam peubah respon.
- **0 < r² < 1** : Proporsi variasi dalam peubah respon dapat dijelaskan oleh peubah prediktor dalam model. Semakin mendekati 1, semakin baik model tersebut dalam menjelaskan variasi.
- **r² = 1** :  Model regresi menjelaskan seluruh variasi dalam peubah respon. Namun, nilai r² yang mencapai 1 mungkin menjadi tanda adanya overfitting.